### ISSUE TITLE
Consider using WPF and blazor

### ISSUE THREAD

**Issue by musictopia2** [AndrewAung11/Pomodoro-Clock#1]
Would you consider using WPF and blazor.
Its very easy to create a webui in blazor.
Can either do in wpf or if you want, the webui can be even in windows forms using the new blazorwebviewcontrol.

**Comment by AndrewAung11** [comment]
I have heard that WPF and blazor are easy but I am afraid I am not familiar with XAML and I want to challenge myself to use bare C#.
Thanks for the suggestion anyway.
