### ISSUE TITLE
UI update suggestions

### ISSUE THREAD

**Issue by Anindra123** [AndrewAung11/Pomodoro-Clock#3]
Hey, your app idea is cool. I have ran it and it works great. But i think few changes will be good. I think it will be better to disable the exit application button when user starts a session and enable it again during break that way user will not slack off after starting a session. Also i think you should turn off the maximise button , currently when it is maximised it awkwardly gets stuck at the corner of the screen.

**Comment by AndrewAung11** [comment]
Oh, thanks for the suggestion!
They sound really good but the thing is that I don't know how I can do that.

**Comment by Anindra123** [comment]
Is it okay if i add those changes and create a pull request ? I will describe and comment out the changes as well for better understanding.

**Comment by AndrewAung11** [comment]
That would be great.
Thanks

**Comment by Anindra123** [comment]
@AndrewAung11  hey i have created the pull request for this and described it on the pull request . Please check it.

**Comment by AndrewAung11** [comment]
Thanks for the help!
