### ISSUE TITLE
Pop up notification box

### ISSUE THREAD

**Issue by Anindra123** [AndrewAung11/Pomodoro-Clock#4]
Showing a pop up notification when a break starts will be great feature i think. I can make a custom one for this project too if you agree.

**Comment by AndrewAung11** [comment]
That would be great. Thanks.

**Comment by AndrewAung11** [comment]
I abandoned the project for nearly a year. 😁
I am back now and I have added this pop up dialog thing.
[Here is the commit](https://github.com/AndrewAung11/Pomodoro-Clock/commit/e950c05203570d1ad3d93f45e38e00ff27798556)
Thanks for the help on other dialog -- I learnt from it and made this.
