### ISSUE TITLE
Name Mismatch: PomodoroClock Class is in Form1.cs file, renaming file suggested

### ISSUE THREAD

**Issue by pjlplourde** [AndrewAung11/Pomodoro-Clock#6]
Normally, the file name should match the class name.  In this case, the file name is Form1.cs, with the autogenerated designer file in Form1.Designer.cs and the resources in Form1.resx, but the class name is PomodoroClock.  Best practice would suggest renaming the files to match the class name.

**Comment by AndrewAung11** [comment]
Thanks for pointing it out! I have changed the name now.
